WITH ranked_transacoes AS (
    SELECT 
        CD_CLIENTE,
        VR_TRANSACAO,
        ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY DT_TRANSACAO DESC) AS ranking
    FROM TbTransacoes
)

SELECT 
    CD_CLIENTE,
    SUM(VR_TRANSACAO) AS SOMA_TRANSACOES,
    COUNT(VR_TRANSACAO) AS NUM_TRANSACOES,
    SUM(VR_TRANSACAO) / COUNT(VR_TRANSACAO) AS TICKET_MEDIO
FROM ranked_transacoes
WHERE ranking <= 4
GROUP BY CD_CLIENTE
ORDER BY CD_CLIENTE;