SELECT 
    t1.CD_CLIENTE,
    t1.CD_TRANSACAO,
    MAX(t1.DT_TRANSACAO) AS ULTIMA_DT_TRANSACAO,
    (
        SELECT t2.VR_TRANSACAO
        FROM TbTransacoes t2
        WHERE t2.CD_CLIENTE = t1.CD_CLIENTE 
        AND t2.CD_TRANSACAO = t1.CD_TRANSACAO
        ORDER BY t2.DT_TRANSACAO DESC
        LIMIT 1
    ) AS ULTIMO_VALOR_TRANSACAO
FROM TbTransacoes t1
GROUP BY t1.CD_CLIENTE, t1.CD_TRANSACAO
ORDER BY t1.CD_CLIENTE, t1.CD_TRANSACAO;