WITH ultima_transacao AS (
    SELECT 
        CD_CLIENTE,
        CD_TRANSACAO,
        DATE_FORMAT(DT_TRANSACAO, '%Y-%m') AS MES_ANO,
        DT_TRANSACAO,
        VR_TRANSACAO,
        RANK() OVER (
            PARTITION BY CD_CLIENTE, CD_TRANSACAO, DATE_FORMAT(DT_TRANSACAO, '%Y-%m') 
            ORDER BY DT_TRANSACAO DESC
        ) AS rnk
    FROM TbTransacoes
)
SELECT 
    CD_CLIENTE,
    CD_TRANSACAO,
    MES_ANO,
    DT_TRANSACAO AS ULTIMA_DT_TRANSACAO,
    VR_TRANSACAO AS ULTIMO_VALOR_TRANSACAO
FROM ultima_transacao
WHERE rnk = 1
ORDER BY CD_CLIENTE, CD_TRANSACAO, MES_ANO;
