SELECT 
    (SUM(CASE WHEN CD_TRANSACAO = '110' THEN VR_TRANSACAO ELSE 0 END) +
     SUM(CASE WHEN CD_TRANSACAO = '000' THEN VR_TRANSACAO ELSE 0 END) -
     SUM(CASE WHEN CD_TRANSACAO = '220' THEN VR_TRANSACAO ELSE 0 END)) AS balanço
FROM TbTransacoes;